$Usamp_Login_Username='vipul_paikane@persistent.co.in'
$Usamp_Login_Password='test'
$Surveyhead_Login_Username='kane_spanish@mailop.com'
$Surveyhead_Login_Password='test'
$mail_initial='Mail_Reward'
$Reward='Automation'
