$Surveyhead_Login_Username='Cashout_Mail_Test.des@mailop.com'
$Surveyhead_Login_Password='test'
$Paypal_Email_id='Cashout_Mail_Test.des@mailop.com'
$Usamp_Login_Username='vipul_paikane@persistent.co.in'
$Usamp_Login_Password='test'