$Usamp_Login_Username='vipul_paikane@persistent.co.in'
$Usamp_Login_Password='test'
$Publisher_Id='PU608'
$Project_Id='PR7368'
$Publisher_Name='IDG_EDAGeek'
$Publisher_Email='miriam_talamini19@idgtechnet.comxyz'
$Mail_Initial="test1234"
$QG_Close_Date="2011-11-30"
$Publisher_Fee="1"
$Success_Pub_Redirect="http://www.google.co.in/Success?mid=%%MID%%&spid=%%SP%%&s=%%S%%"
$Fail_Pub_Redirect="http://www.google.co.in/Fail?mid=%%MID%%&spid=%%SP%%&s=%%S%%"
$Overquota_Pub_Redirect="http://www.google.co.in/Overquota?mid=%%MID%%&spid=%%SP%%&s=%%S%%"
$pl1="2"
$pl2="0"
$pl3="6"