module MemberData
  FNAME = "Nitin"
  LNAME = "Kumar"
  COUNTRY = "United States"
  LANGUAGE = "English"
  STATE = "California"
  ZIP_CODE = "90001"
  DATE = "08"
  MONTH = "April"
  YEAR = "1980"
  EMAIL = "test22_des@mailop.com"
  MAIL = "test22.des"
  PASSWORD = "test"
  INCOME = "19,999 or less"
  EDUCATION = "High school graduate"
  EMPLOYMENT = "Full-Time Employee"
  INDUSTRY = "Computers: Software / Services"
  ROLE = "Executives"
  JOB_TITLE = "Partner"
  ETHNICITY = "African American"
  MARITIAL_STATUS = "Never married"
  COUNTRY_ORIGIN = "United States"
  CHILDREN = "N"
  INVITE = "0"
end

