$qg_id = "47674"
$QG_STATUS = "Setting Up"
$QG_CLOSE_DATE = "2010-12-30"
$N_Sample_Size = "100"
$INCIDENCE = "2"
$INCIDENCE_RANGE = "General_population"
$QG_CATEGORY = "Business"
$LENGTH	 = "Time"
$TIME_QNS = "2"
$CPI	 = "10"
$REW_TYPE = "Cash"
$REW_AMOUNT = "10"
$NEW_REW_AMOUNT = "20"
$FAIL_REW_AMT = "1"
$OVERQUOTA_REW_AMT = "1"
$SURVEY_URL = "http://203.199.26.75/usamp/TEST_SURVEY.php"
$PUBLISHER_NAME = "Test PUB (30 Sept)"

$usamp_email = "rahul_halankar@persistent.co.in"
$usamp_passwd = "rahul123"

$Country = "United States"
$Language1 = "English"
$Lower_Age = "10"
$Upper_age = "99"
$Gender = "Male"
$Origin = "American Samoa"
$Education = "High school graduate"
$Employment = "Full-Time Employee"
$Industry = "Agribusiness"
$Maritial_status = "Separated"
$Language = "Arabic"
$username = "test_desautomation@mailop.com"
$member_id = "4583453"
$template_name = "Test_template"
$extension = Time.new
$extension = $extension.to_s
$extension = $extension.slice(13..18)
$template_name = $template_name+$extension
$template_name = $template_name.gsub(/:/, "")
puts $template_name
